// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import NestedForm from "stimulus-rails-nested-form";
application.register("nested-form", NestedForm);
import HighlightController from "./highlight_controller";
application.register("highlight", HighlightController);
import ResizeWidthController from "./resize_width_controller";
application.register("resize-width", ResizeWidthController);
import ResizeHeightController from "./resize_height_controller";
application.register("resize-height", ResizeHeightController);
